services:

  fit-api:
    build:
      context: .
      dockerfile: api/FitHappens.WebApi/Dockerfile
    image: fit-happens/fit-api:latest
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ./../data/fit-api:/app/data
    ports:
      - "8080:8080"

  fit-web:
    build:
      context: .
      dockerfile: shared/ts/apps/fit-web/Dockerfile
    image: fit-happens/fit-web:latest
    restart: unless-stopped
    ports:
      - "4201:80"
