// source: protos/journal.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.google.protobuf.CreateSetMsg');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.MessageStamp');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.protobuf.CreateSetMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.protobuf.CreateSetMsg.repeatedFields_, null);
};
goog.inherits(proto.google.protobuf.CreateSetMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.protobuf.CreateSetMsg.displayName = 'proto.google.protobuf.CreateSetMsg';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.protobuf.CreateSetMsg.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.protobuf.CreateSetMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.google.protobuf.CreateSetMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.protobuf.CreateSetMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.CreateSetMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
stamp: (f = msg.getStamp()) && proto.google.protobuf.MessageStamp.toObject(includeInstance, f),
id: jspb.Message.getFieldWithDefault(msg, 2, ""),
timestamp: jspb.Message.getFieldWithDefault(msg, 3, 0),
exerciseid: jspb.Message.getFieldWithDefault(msg, 4, ""),
reps: jspb.Message.getFieldWithDefault(msg, 5, 0),
tagidsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.protobuf.CreateSetMsg}
 */
proto.google.protobuf.CreateSetMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.protobuf.CreateSetMsg;
  return proto.google.protobuf.CreateSetMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.protobuf.CreateSetMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.protobuf.CreateSetMsg}
 */
proto.google.protobuf.CreateSetMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.protobuf.MessageStamp;
      reader.readMessage(value,proto.google.protobuf.MessageStamp.deserializeBinaryFromReader);
      msg.setStamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setExerciseid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReps(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addTagids(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.protobuf.CreateSetMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.protobuf.CreateSetMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.protobuf.CreateSetMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.protobuf.CreateSetMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStamp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.protobuf.MessageStamp.serializeBinaryToWriter
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getExerciseid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getReps();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getTagidsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
};


/**
 * optional MessageStamp stamp = 1;
 * @return {?proto.google.protobuf.MessageStamp}
 */
proto.google.protobuf.CreateSetMsg.prototype.getStamp = function() {
  return /** @type{?proto.google.protobuf.MessageStamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.MessageStamp, 1));
};


/**
 * @param {?proto.google.protobuf.MessageStamp|undefined} value
 * @return {!proto.google.protobuf.CreateSetMsg} returns this
*/
proto.google.protobuf.CreateSetMsg.prototype.setStamp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.protobuf.CreateSetMsg} returns this
 */
proto.google.protobuf.CreateSetMsg.prototype.clearStamp = function() {
  return this.setStamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.protobuf.CreateSetMsg.prototype.hasStamp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.google.protobuf.CreateSetMsg.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.protobuf.CreateSetMsg} returns this
 */
proto.google.protobuf.CreateSetMsg.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 timestamp = 3;
 * @return {number}
 */
proto.google.protobuf.CreateSetMsg.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.protobuf.CreateSetMsg} returns this
 */
proto.google.protobuf.CreateSetMsg.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string exerciseId = 4;
 * @return {string}
 */
proto.google.protobuf.CreateSetMsg.prototype.getExerciseid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.protobuf.CreateSetMsg} returns this
 */
proto.google.protobuf.CreateSetMsg.prototype.setExerciseid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 reps = 5;
 * @return {number}
 */
proto.google.protobuf.CreateSetMsg.prototype.getReps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.protobuf.CreateSetMsg} returns this
 */
proto.google.protobuf.CreateSetMsg.prototype.setReps = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated string tagIds = 6;
 * @return {!Array<string>}
 */
proto.google.protobuf.CreateSetMsg.prototype.getTagidsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.protobuf.CreateSetMsg} returns this
 */
proto.google.protobuf.CreateSetMsg.prototype.setTagidsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.CreateSetMsg} returns this
 */
proto.google.protobuf.CreateSetMsg.prototype.addTagids = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.protobuf.CreateSetMsg} returns this
 */
proto.google.protobuf.CreateSetMsg.prototype.clearTagidsList = function() {
  return this.setTagidsList([]);
};


